#!/usr/bin/env python3
"""Generate TypeScript gateway contracts from ``tui_gateway.contracts``."""

from __future__ import annotations

import os
from pathlib import Path
from tempfile import NamedTemporaryFile

import ts_type as ts
from hermes_cli.contract_types import DocumentedContractBuilder
from hermes_cli.web_contracts import EXPORTED_CONTRACTS
from tui_gateway.contracts import (
    GatewayMcpServerStatus,
    GatewayProjectInfo,
    GatewaySessionRuntimeInfo,
    GatewayUsage,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "apps/shared/src/generated/gateway.ts"


def main() -> None:
    for contract in (
        GatewayMcpServerStatus,
        GatewayProjectInfo,
        GatewayUsage,
        GatewaySessionRuntimeInfo,
    ):
        ts.generator.add(contract, "gateway", contract.__name__)
    for name, contract in EXPORTED_CONTRACTS.items():
        ts.generator.add(contract, "gateway", name)

    source = ts.generator.render(builder_cls=DocumentedContractBuilder)["gateway"]
    output = "// Generated by scripts/generate_gateway_types.py. Do not edit.\n\n" + source + "\n"
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    # Workspace checks may run concurrently. Replacing an already-complete
    # temporary file means a typecheck always observes either version, never a
    # partially-written module.
    with NamedTemporaryFile("w", encoding="utf-8", dir=OUTPUT.parent, delete=False) as file:
        file.write(output)
        temp_path = Path(file.name)
    os.replace(temp_path, OUTPUT)


if __name__ == "__main__":
    main()
